#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from subprocess import run
from sys import stdout, stdin, stderr
import os
from pathlib import Path
from os.path import abspath, basename, commonpath, dirname, exists, isfile, isdir, isabs, commonprefix
from argparse import ArgumentParser
import argparse
import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()

logger.info('declaring an ArgParser')

parser = ArgumentParser(description='A generic sorter.')

parser.add_argument('infile',
                    type=argparse.FileType('r'),
                    nargs='?',
                    default='-')
logger.info('adding infile arg')

parser.add_argument('outfile',
                    nargs='?',
                    type=argparse.FileType('w'),
                    default='stdout')
logger.info('adding outfile arg')

args = parser.parse_args()

# assert Path(args.infile).exists()

logger.info('parsing args')

args = parser.parse_args()

logger.info('parsed')

logger.info('about to print')

[print(j, end='') for j in sorted([i for i in args.infile])]



def main():
    pass
